### ISSUE TITLE
TK crashes on MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by kostas-stathis** [dicelab-rhul/vacuumworld#102]
All versions of VW use TK for the GUI. TK causes crashes on MacOS Catalina 10.15.7 (see below).

2021-06-19 17:12:38.524 Python[64264:7281928] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff38856627 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff716ef5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3887ee0c -[NSException raise] + 9
	3   AppKit                              0x00007fff35a795ec -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
	4   AppKit                              0x00007fff35a61052 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	5   AppKit                              0x00007fff35a60ac3 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   Tk                                  0x00007fff4638b38b TkMacOSXMakeRealWindowExist + 763
	7   Tk                                  0x00007fff4638afb9 TkWmMapWindow + 56
	8   Tk                                  0x00007fff462ff19a Tk_MapWindow + 155
	9   Tk                                  0x00007fff4630728e TkInstallFrameMenu + 271
	10  Tcl                                 0x00007fff462999d1 TclServiceIdle + 75
	11  Tcl                                 0x00007fff462812a1 Tcl_DoOneEvent + 340
	12  Tk                                  0x00007fff462e05cd TkGetDisplayOf + 917
	13  Tcl                                 0x00007fff4621797f Tcl_ListMathFuncs + 1787
	14  Tcl                                 0x00007fff4621821e Tcl_EvalObjv + 57
	15  _tkinter.cpython-38-darwin.so       0x000000010cc3c970 Tkapp_Call + 480
	16  Python3                             0x000000010c34966e method_vectorcall_VARARGS + 270
	17  Python3                             0x000000010c4202c2 call_function + 354
	18  Python3                             0x000000010c41c969 _PyEval_EvalFrameDefault + 29753
	19  Python3                             0x000000010c340a3d function_code_fastcall + 237
	20  Python3                             0x000000010c3433fb method_vectorcall + 171
	21  Python3                             0x000000010c4202c2 call_function + 354
	22  Python3                             0x000000010c41c986 _PyEval_EvalFrameDefault + 29782
	23  Python3                             0x000000010c340a3d function_code_fastcall + 237
	24  Python3                             0x000000010c4202c2 call_function + 354
	25  Python3                             0x000000010c41c969 _PyEval_EvalFrameDefault + 29753
	26  Python3                             0x000000010c340a3d function_code_fastcall + 237
	27  Python3                             0x000000010c4202c2 call_function + 354
	28  Python3                             0x000000010c41c969 _PyEval_EvalFrameDefault + 29753
	29  Python3                             0x000000010c340a3d function_code_fastcall + 237
	30  Python3                             0x000000010c4202c2 call_function + 354
	31  Python3                             0x000000010c41c969 _PyEval_EvalFrameDefault + 29753
	32  Python3                             0x000000010c340a3d function_code_fastcall + 237
	33  Python3                             0x000000010c343492 method_vectorcall + 322
	34  Python3                             0x000000010c3403d4 PyVectorcall_Call + 100
	35  Python3                             0x000000010c4c20ea t_bootstrap + 74
	36  Python3                             0x000000010c473ad9 pythread_wrapper + 25
	37  libsystem_pthread.dylib             0x00007fff72a9c109 _pthread_start + 148
	38  libsystem_pthread.dylib             0x00007fff72a97b8b thread_start + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by cloudstrife9999** [comment]
Fixed by #104.
