### ISSUE TITLE
Phantom dirt

### ISSUE THREAD

**Issue by JanWanot** [dicelab-rhul/vacuumworld#11]
Sometimes the GUI map of the level shows a phantom dirt after it has already been collected. The phantom dirt persists even after the map size has been changed.

Steps to reproduce:
As the robot makes its way around the map, often it will slow down and lag for a few seconds. Afterwards it will make several actions at once in a rapid succession. If one of these actions was collecting dirt, then it the dirt will sometimes be collected in the game logic, but remain on the screen as phantom dirt.

Since this effect is tied to the slowdown and the slowdown is very inconsistant, I have found that no setup can cause phantom dirt 100% of the time. However setups where there is a lot of dirt on the edges of the map seem to have a good chance in my experience. 

Vacuumworld version (from pip show vacuumworld):
4.1.6
MacOS Mojave version:
10.14.6 (18G103)
Python version:
3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)]

**Comment by BenedictWilkinsAI** [comment]
Thank you Jan,

The slow down you mentioned is an issue with the interaction of MacOS with python multi-threading. Unfortunately I have not yet found a way around this. I will investigate this "phantom dirt" bug further. To avoid it, I suggest using the teaching server (or a different OS), this will make testing a lot easier for you as they dont suffer from the same issues!

Best,
Ben

**Comment by BenedictWilkinsAI** [comment]
It turns out that this issue may be related (or the same as) another issue - if you place and agent (or dirt) at the edge of the grid with the mouse off the edge of the window, it does not register that the agent (or dirt) was placed but is left in the GUI i.e. it will become a phantom.

**Comment by cloudstrife9999** [comment]
Fixed by #35.
