### ISSUE TITLE
typo issue

### ISSUE THREAD

**Issue by mathieufiani** [dicelab-rhul/vacuumworld#14]
the function observation is called obsevation (R missing)

**Comment by cloudstrife9999** [comment]
Hi @mathieufiani , thank you for reporting this. Can you please be more precise about the relevant file and line? I cannot find it, at the moment.

**Comment by cloudstrife9999** [comment]
As I could not find the misspelling within the code (or within the wiki), I assume it was fixed some time in the past.

As such, I'm closing the issue.
