### ISSUE TITLE
Providing different colour minds to run()

### ISSUE THREAD

**Issue by Pickersgill** [dicelab-rhul/vacuumworld#16]
The documentation describes being able to pass different minds (for each colour) to run() as follows:
```python
run(white_mind, green_mind, orange_mind)
```
This works perfectly as intended as long as you provide all three, and they're passed in the given order. The documentation ([6.2 of the guide](https://moodle.royalholloway.ac.uk/mod/resource/view.php?id=377666) and [page 6 of the wiki](https://github.com/dicelab-rhul/vacuumworld/wiki/6\)-Installing-and-Running)) is not very clear about how this works and it would be nice to be able to provide different colour minds individually as keyword arguments:
```python
run(green_mind=my_mind_object, orange_mind=my_other_mind_object)
```

**Comment by Pickersgill** [comment]
The [source code for vacuumworld.run()](https://github.com/dicelab-rhul/vacuumworld/blob/master/vacuumworld/__init__.py) already includes keywords for each non-white colour mind but requires a white mind to be passed:
```python
def run(white_mind, green_mind=None, orange_mind=None, **kwargs) ...
```
It would be helpful to amend the documentation to describe this. 

Alternatively, perhaps a default mind could be provided as a positional argument and white_mind given as a keyword in conjunction (as with orange_mind and green_mind)?
```python
def run(default_mind, white_mind=None, green_mind=None, orange_mind=None, **kwargs) ...
```
Unless there is a reason for the current approach.

**Comment by cloudstrife9999** [comment]
What do you think @BenedictWilkinsAI ?

For reference, #17 .

**Comment by cloudstrife9999** [comment]
After discussing with Ben, I amended the code, and enriched the wiki.

As of eb1d95c, the behaviour of `default_mind`, `white_mind`, `green_mind`, and `orange_mind` has been slightly changed.

See https://github.com/dicelab-rhul/vacuumworld/wiki/6)-Installing-and-Running for further details.

**Comment by cloudstrife9999** [comment]
If no further problem arises, I'm closing the issue in 24 hours.
