### ISSUE TITLE
auto resolution 

### ISSUE THREAD

**Issue by BenedictWilkinsAI** [dicelab-rhul/vacuumworld#39]
Currently there is a work around for different screen resolutions -- there is an optional parameter in vacuumworld.start that changes the display scale. 

It would be nice to auto-detect screen resolution and scale accordingly (people with 4k screens have issues basically).

**Comment by cloudstrife9999** [comment]
Solved by #40. Unfortunately, there is no way to zoom/resize the title bar in TK, unless a new title bar is created from scratch.
