### ISSUE TITLE
Add option to turn off tooltips

### ISSUE THREAD

**Issue by BenedictWilkinsAI** [dicelab-rhul/vacuumworld#48]
Not a fan of tools tips all the time... would be nice to have the option of turning them off in `vacuumworld.run`

**Comment by cloudstrife9999** [comment]
I'm adding a **tooltip** boolean parameter that determines whether the tooltips are enabled or not.
I'm making it so that, if it is omitted, the tooltips are **ON** by default.

**Comment by cloudstrife9999** [comment]
Done in #52.
