### ISSUE TITLE
Extend the size slider to fit with new buttons.

### ISSUE THREAD

**Issue by BenedictWilkinsAI** [dicelab-rhul/vacuumworld#49]
The new "?" button means the size slider doesnt fit to the buttons widths... maybe we can make the slider a bit longer (this is pretty minor...)

**Comment by BenedictWilkinsAI** [comment]
Either that or have some discussion about whether "?" is needed (given there is a link to the guide on the title page)

**Comment by cloudstrife9999** [comment]
Fixed by #51.
