### ISSUE TITLE
Window scaling on high DPI screens

### ISSUE THREAD

**Issue by Juici** [dicelab-rhul/vacuumworld#6]
```
OS: Manjaro Linux x86_64 
Kernel: 4.19.69-1-MANJARO 
Resolution: 3840x2160

Python Version: 3.7.4
```

The window is tiny on high DPI screens.

A solution for linux-based systems would be to respect the desktop environment scale factor. Using environment variables like `GDK_SCALE`.

eg.
```
import os

SCALE = float(os.getenv('GDK_SCALE', 1))
```

I believe Windows also has DPI aware functions in the API.

**Comment by BenedictWilkinsAI** [comment]
Hello Juici, 

I have added a scale option in vacuumworld.run as a temporary solution to this. This should work for now, in the next major update I will make the GUI resizable and remove the need for this.

Example use:
`vacuumworld.run(MyMind(), scale=2)`

The pip repo will be updated when testing has been done on various machines. We would be grateful if you can test on your machine and feedback.

Let me know if you find any further issues with this!
Best,
Ben
